---
name: "deploy_docker_diplomovka_app"
pack: "st2_diplomovka_app"
description: "Deployne docker diplomovka-app na base server"
enabled: true

type:
  ref: "standard"

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "deploy-diplomovka-docker-base"

action:
  parameters:
    # Parametre posielane v payloade webhook-u
    app_version: "{{ trigger.body.app_version }}"
    app: "{{ trigger.body.app_artifact_id }}"
    docker_host: "diplomovka-app-01"
    env: "(BASE)"
    project_tag: "DIPLOMOVKA"
    saltmaster: "diplomovka-ops"
    dockercompose_path: "/opt/diplomovka_compose"
    docker_repository: "therdvn"
  ref: "st2_diplomovka_app.deploy_docker_app.yaml"